// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDqwJb3fDjjF-aycxVx8rCzrrPY4FuVqU',
    appId: '1:947731786438:web:2fcec688609468424ac5c7',
    messagingSenderId: '947731786438',
    projectId: 'user-information-d6559',
    authDomain: 'user-information-d6559.firebaseapp.com',
    storageBucket: 'user-information-d6559.firebasestorage.app',
    measurementId: 'G-PSQC4G04V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASh0zONkUVW6x7PW8JQrem66MyPsFquVo',
    appId: '1:947731786438:android:c195ca8c8105055e4ac5c7',
    messagingSenderId: '947731786438',
    projectId: 'user-information-d6559',
    storageBucket: 'user-information-d6559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxcjA8-6studrxliqoRu0owD19dyq0Bk',
    appId: '1:947731786438:ios:b3e516a49cebbc314ac5c7',
    messagingSenderId: '947731786438',
    projectId: 'user-information-d6559',
    storageBucket: 'user-information-d6559.firebasestorage.app',
    iosBundleId: 'com.example.userInformation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHxcjA8-6studrxliqoRu0owD19dyq0Bk',
    appId: '1:947731786438:ios:b3e516a49cebbc314ac5c7',
    messagingSenderId: '947731786438',
    projectId: 'user-information-d6559',
    storageBucket: 'user-information-d6559.firebasestorage.app',
    iosBundleId: 'com.example.userInformation',
  );
}
