// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlbgivuSN-PLzavSQfQeuHmbhrsLgRzE',
    appId: '1:206904742858:web:6a7a942f7b91063b737533',
    messagingSenderId: '206904742858',
    projectId: 'user-information-95136',
    authDomain: 'user-information-95136.firebaseapp.com',
    storageBucket: 'user-information-95136.firebasestorage.app',
    measurementId: 'G-DHNE30HKJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6adzRll3_zLb5mLSFfaB03r6SaM6rAAA',
    appId: '1:206904742858:android:24557ecac31f7d3e737533',
    messagingSenderId: '206904742858',
    projectId: 'user-information-95136',
    storageBucket: 'user-information-95136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtiwrqH77qScD0F_FJj-twwRFsZVbzf1E',
    appId: '1:206904742858:ios:81a06e93eb2b9aa6737533',
    messagingSenderId: '206904742858',
    projectId: 'user-information-95136',
    storageBucket: 'user-information-95136.firebasestorage.app',
    iosBundleId: 'com.example.userInformation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtiwrqH77qScD0F_FJj-twwRFsZVbzf1E',
    appId: '1:206904742858:ios:81a06e93eb2b9aa6737533',
    messagingSenderId: '206904742858',
    projectId: 'user-information-95136',
    storageBucket: 'user-information-95136.firebasestorage.app',
    iosBundleId: 'com.example.userInformation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPlbgivuSN-PLzavSQfQeuHmbhrsLgRzE',
    appId: '1:206904742858:web:d87c76e67004864b737533',
    messagingSenderId: '206904742858',
    projectId: 'user-information-95136',
    authDomain: 'user-information-95136.firebaseapp.com',
    storageBucket: 'user-information-95136.firebasestorage.app',
    measurementId: 'G-D2MSNWTKR6',
  );
}
